### ISSUE TITLE
Roadmap v6

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#189]
Roadmap for the next major release:

- [x] ~~Migrate to TypeScript (all the codebase)~~.
- [x] ~~Split codebase into multiple workspaces~~
- [x] Refactor codebase (focus on testing).

Re-implement external packages into the Scanner workspace:
- [x] license-conformance, npm-tarball-license-parser
- [x] authors (see https://github.com/NodeSecure/scanner/issues/224)

**Comment by jean-michelet** [comment]
I can help migrate to TypeScript, do you have more specific recommendations?

**Comment by fraxken** [comment]
@jean-michelet I already started here: https://github.com/NodeSecure/scanner/pull/195 (just didn't found the time to continue yet)
