### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#284]
- [ ] Remove detection logics from tree-walker and remove Dependency class (instead return a simple Object with pacote manifest raw data)
- [x] Implement vulnera major 2
- [ ] Refactor/Re-implement tarball workspace ( see #379 )
- [ ] Implement JS-X-Ray [EntryFileAnalyser](https://github.com/NodeSecure/js-x-ray/blob/master/docs/api/EntryFilesAnalyser.md) to reduce the number of false positives ( see #379 )

Continue the effort to add more tests and improve each workspaces documentation.
